###
# @license
# Heye Vöcking All Rights Reserved.
#
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file at https://telepathy.app/license
##

addons:
  apt:
    packages:
      - docker-ce
language: bash
services:
  - docker
script: make travis
