version: '3.4'
services:
  appium:
    image: telepathy/appium.files
    depends_on:
      - selenium-hub
    env_file: .env
    environment:
      APPIUM: 'true'
      APPIUM_HOST: '${ENV_APPIUM_HOST}'
      APPIUM_PORT: '${ENV_APPIUM_PORT}'
      CONNECT_TO_GRID: 'true'
      DEVICE: Samsung Galaxy S6
      MOBILE_WEB_TEST: 'true'
      SELENIUM_HOST: '${ENV_SELENIUM_HOST}'
      SELENIUM_PORT: '${ENV_SELENIUM_PORT}'
    networks:
      default:
        aliases:
          - '${ENV_APPIUM_HOST}'
    ports:
      - '${ENV_APPIUM_PORT}:${ENV_APPIUM_PORT}'
      - '6080:6080'
      - '5554:5554'
      - '5555:5555'
    privileged: true

  chrome-debug:
    image: telepathy/chrome-debug.setup
    depends_on:
      - selenium-hub
    env_file: .env
    environment:
      ENV_FRONTEND_HOST: '${ENV_FRONTEND_HOST}'
      ENV_FRONTEND_PORT: '${ENV_FRONTEND_PORT}'
      HUB_PORT_4444_TCP_ADDR: '${ENV_SELENIUM_HOST}'
      HUB_PORT_4444_TCP_PORT: '${ENV_SELENIUM_PORT}'
    ports:
      - '5900:5900'

  ci:
    command: ci
    depends_on:
      - chrome-debug
      - appium
    env_file: .env
    image: telepathy/frontend.dist
    ports:
      - '${ENV_FRONTEND_PORT}:${ENV_FRONTEND_PORT}'
    networks:
      default:
        aliases:
          - '${ENV_FRONTEND_HOST}'

  lint:
    command: tail -f config/profile
    image: telepathy/lint.setup
    volumes:
      - '${PWD}/lint:${ENV_DOCKER_PROJECT_ROOT}'
      - '${PWD}/.git:${ENV_DOCKER_PROJECT_ROOT}/.git'

  selenium-hub:
    env_file: .env
    environment:
      GRID_TIMEOUT: 10000
    hostname: '${ENV_SELENIUM_HOST}'
    image: selenium/hub:3.141.59-antimony
    ports:
      - '${ENV_SELENIUM_PORT}:${ENV_SELENIUM_PORT}'
    networks:
      default:
        aliases:
          - '${ENV_SELENIUM_HOST}'

  travis:
    command: travis
    depends_on:
      - chrome-debug
    env_file: .env
    image: telepathy/frontend.dist
    ports:
      - '${ENV_FRONTEND_PORT}:${ENV_FRONTEND_PORT}'
    networks:
      default:
        aliases:
          - '${ENV_FRONTEND_HOST}'

  watch:
    command: watch
    depends_on:
      - chrome-debug
      - serve
    env_file: .env
    image: telepathy/frontend.setup
    volumes:
      - '${PROJECT_ROOT}/frontend:${ENV_DOCKER_PROJECT_ROOT}/'
