version: '3.4'
services:

  android:
    command: dist
    env_file: .env
    image: telepathy/android.setup
    privileged: true
    volumes:
      - '${PROJECT_ROOT}/frontend:/input/frontend'
      - '${PROJECT_ROOT}/output/android:/output'
      - '${PROJECT_ROOT}/android/platforms:${ENV_DOCKER_USER_HOME}/android-sdk/platforms/'
      - '${PROJECT_ROOT}/android/.gradle:${ENV_DOCKER_USER_HOME}/.gradle/'
      - '${PROJECT_ROOT}/android/.android:${ENV_DOCKER_USER_HOME}/.android/'
      - '/dev/bus/usb:/dev/bus/usb'

  caddy:
    cap_add:
      - NET_BIND_SERVICE
    command: serve
    container_name: caddy
    depends_on:
      - ipfs
    env_file: .env
    hostname: caddy
    image: telepathy/caddy.files:latest
    networks:
      default:
        aliases:
          - "${ENV_CADDY_HOST}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '${DATA_DIR}/${ENV_VERSION_BUILD_TYPE}/caddy:/data/caddy'
    user: app

  publish:
    command: dist
    env_file: .env
    image: telepathy/ipfs.dist:latest
    volumes:
      - '${DATA_DIR}/${ENV_VERSION_BUILD_TYPE}/ipfs:/data/ipfs'
    user: app

  ipfs:
    command: serve
    container_name: ipfs
    env_file: .env
    hostname: ipfs
    image: telepathy/ipfs.files:latest
    networks:
      default:
        aliases:
          - "${ENV_IPFS_HOST}"
    ports:
      - "${ENV_IPFS_API_PORT}:${ENV_IPFS_API_PORT}"
      - "${ENV_IPFS_GATEWAY_PORT}:${ENV_IPFS_GATEWAY_PORT}"
      - "${ENV_IPFS_TCP_PORT}:${ENV_IPFS_TCP_PORT}"
      - "${ENV_IPFS_WEBSOCKET_PORT}:${ENV_IPFS_WEBSOCKET_PORT}"
    volumes:
      - "${PROJECT_ROOT}/ipfs:${ENV_DOCKER_PROJECT_ROOT}/"
      - '${DATA_DIR}/${ENV_VERSION_BUILD_TYPE}/ipfs:/data/ipfs'
    user: app

  serve:
    command: serve
    depends_on:
      - caddy
    env_file: .env
    image: telepathy/frontend.setup
    ports:
      - '${ENV_FRONTEND_LAB_PORT}:${ENV_FRONTEND_LAB_PORT}'
      - '${ENV_FRONTEND_PORT}:${ENV_FRONTEND_PORT}'
      - '${ENV_FRONTEND_LIVERELOAD_PORT}:${ENV_FRONTEND_LIVERELOAD_PORT}'
    networks:
      default:
        aliases:
          - '${ENV_FRONTEND_HOST}'
    volumes:
      - '${PROJECT_ROOT}/frontend:${ENV_DOCKER_PROJECT_ROOT}/'
