###
# @license
# Heye Vöcking All Rights Reserved.
#
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file at https://telepathy.app/license
##

FROM node:10-alpine
RUN : \
  && apk update \
  && apk upgrade \
  && apk add --no-cache \
    bash \
    git \
;
RUN npm i -g @commitlint/cli @commitlint/config-conventional
WORKDIR /app
ENTRYPOINT ["commitlint"]
CMD [" --from", "HEAD"]
