#!/usr/bin/env bash

###
# @license
# Heye Vöcking All Rights Reserved.
#
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file at https://telepathy.app/license
##

set -euo pipefail

OP=$1; shift
BUCKETS=${@:-buckets/*}

for BUCKET in $BUCKETS
do
  BUCKET=${BUCKET##buckets/}
  if [[ $OP == read ]]
  then
    gsutil rsync -r "gs://$BUCKET" "/mnt/buckets/$BUCKET"
  elif [[ $OP == write ]]
  then
    gsutil rsync -dr "/mnt/buckets/$BUCKET" "gs://$BUCKET"
  fi
done
