#!/usr/bin/env bash

###
# @license
# Heye Vöcking All Rights Reserved.
#
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file at https://telepathy.app/license
##

set -euo pipefail

$(dirname $0)/run-google-cloud-sdk

docker exec \
  -it \
  gcloud-config \
  gsutil \
  $@ \
;
